// Generated by https://quicktype.io
//
// To change quicktype's target language, run command:
//
//   "Set quicktype target language"

namespace QuickType
{
    using System;
    using System.Collections.Generic;

    using System.Globalization;
    using Newtonsoft.Json;
    using Newtonsoft.Json.Converters;

    public partial class WorkFlow
    {
        [JsonProperty("WorkflowName")]
        public string WorkflowName { get; set; }

        [JsonProperty("Rules")]
        public Rule[] Rules { get; set; }
    }

    public partial class Rule
    {
        [JsonProperty("RuleName")]
        public string RuleName { get; set; }

        [JsonProperty("Expression")]
        public string Expression { get; set; }
    }

    public partial class WorkFlow
    {
        public static WorkFlow[] FromJson(string json) => JsonConvert.DeserializeObject<WorkFlow[]>(json, QuickType.Converter.Settings);
    }

    public static class Serialize
    {
        public static string ToJson(this WorkFlow[] self) => JsonConvert.SerializeObject(self, QuickType.Converter.Settings);
    }

    internal static class Converter
    {
        public static readonly JsonSerializerSettings Settings = new JsonSerializerSettings
        {
            MetadataPropertyHandling = MetadataPropertyHandling.Ignore,
            DateParseHandling = DateParseHandling.None,
            Converters = {
                new IsoDateTimeConverter { DateTimeStyles = DateTimeStyles.AssumeUniversal }
            },
        };
    }
}
